FROM ocaml/opam:alpine-3.6-ocaml-4.04.2 as builder

WORKDIR /core-network
ADD core-network.export core-network.export

RUN sudo apk --no-cache add --update \
    alpine-sdk \
    autoconf \
    bash \
    gmp-dev \
    linux-headers \
    perl \
    && opam pin add -n mirage-net-psock.0.1.0 \
    https://github.com/sevenEng/mirage-net-psock.git \
    && opam switch import core-network.export

ADD . .
RUN sudo chown opam: -R . && opam config exec -- jbuilder build bin/relay.exe


FROM alpine:3.6

WORKDIR /core-network
RUN apk update && apk add bash gmp-dev iptables iproute2 tcpdump
COPY --from=builder /core-network/_build/default/bin/relay.exe bcast-relay

LABEL databox.type="core-network-broadcast-relay"

ENTRYPOINT ["./bcast-relay"]
